[package]
name = "apt-transport-r2"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "r2"
path = "src/main.rs"

[dependencies]
anyhow = "1"
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-credential-types = { version = "1", features = ["hardcoded-credentials"] }
aws-sdk-s3 = "1"
hex = "0.4"
md-5 = "0.10"
sha2 = "0.10"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }
tempfile = "3"
