[package]
name = "apt-transport-r2"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "r2"
path = "src/main.rs"

[dependencies]
anyhow = "1"
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-credential-types = { version = "1", features = ["hardcoded-credentials"] }
aws-sdk-s3 = "1"
tokio = { version = "1", features = ["full"] }
