name: Build Debian package

on:
  push:
    branches:
    - 'main'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'


permissions:
  contents: write

jobs:
  build-deb:
    name: Build deb for (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    container:
      image: debian:13.5
    strategy:
      matrix:
        include:
        - arch: amd64
          runner: ubuntu-24.04
        - arch: arm64
          runner: ubuntu-24.04-arm
    env:
      DEBIAN_FRONTEND: 'noninteractive'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Install build dependencies
      run: |
        apt update
        apt install -y curl build-essential pkg-config libssl-dev

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Cache Rust
      uses: Swatinem/rust-cache@v2

    - name: Install cargo-deb
      run: cargo install cargo-deb

    - name: Run unit and integration tests
      run: cargo test --all-targets --all-features

    - name: Check formatting
      run: |
        rustup component add rustfmt
        cargo fmt --check

    - name: Check for warnings
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Build deb package
      run: cargo deb

    - name: Upload .deb artifacts
      uses: actions/upload-artifact@v7
      with:
        name: deb-${{ matrix.arch }}
        path: target/debian/*.deb

  installation-test:
    name: Installation smoke test (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    needs: build-deb
    container:
      image: debian:13.5
    strategy:
      matrix:
        include:
        - arch: amd64
          runner: ubuntu-24.04
        - arch: arm64
          runner: ubuntu-24.04-arm
    env:
      DEBIAN_FRONTEND: 'noninteractive'

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        path: artifacts

    - name: Update APT
      run: apt update

    - name: Install package
      run: |
        apt install -y ./artifacts/deb-${{ matrix.arch }}/*_${{ matrix.arch }}.deb

  release:
    name: Create GitHub release
    needs: build-deb
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        path: artifacts

    - name: Create release
      uses: softprops/action-gh-release@v3
      with:
        files: artifacts/**/*

    - name: Trigger APT repo import
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: import-release.yml
        repo: hoefling/apt
        ref: refs/heads/main
        inputs: '{"repo":"${{ github.repository }}","version":"${{ github.ref_name }}"}'
        token: ${{ secrets.APT_REPO_TOKEN }}
